### ISSUE TITLE
Can't use incanter.core/update with Clojure 1.7

### ISSUE THREAD

**Issue by YPares** [incanter/incanter#321]
When trying to call e.g `add-derived-column`, I get this:

`Attempting to call unbound fn: #'incanter.core/update`

And before that (when repl starts) there's a warning that `update` is conflicting with `clojure.core/update`. It's happening only with Clojure 1.7

**Comment by marcomorain** [comment]
:+1:

**Comment by carocad** [comment]
Hey guys since I was having the same warning over an over again. I thought about a possible solution: if the conflict is with clojure's update function and in order not to change the function's name, shouldn't this simple change fix the bug?
```Clojure
(ns incanter.core
    (:refer-clojure :exclude [update])
```
let me know if it helps ;)

**Comment by alexott** [comment]
What version of Incanter do you use?

**Comment by carocad** [comment]
I use incanter/incanter-core "1.5.5"

**Comment by alexott** [comment]
I just pushed Incanter 1.5.7 to clojars...

**Comment by d4goxn** [comment]
I'm still hitting this with Incanter 1.5.7 and Clojure 1.8.0

```
WARNING: update already refers to: #'clojure.core/update in namespace: incanter.core, being replaced by: #'incanter.core/update
Exception in thread "main" java.lang.IllegalStateException: Attempting to call unbound fn: #'incanter.core/update, compiling:(/tmp/form-init1572543805718644027.clj:1:73)
```

**Comment by skliarpawlo** [comment]
ugh, having the same issue, is there any recent clojure version compatible with some recent incanter version?

**Comment by alexott** [comment]
@skliarpawlo are you using 1.5.x or 1.9.x?

**Comment by skliarpawlo** [comment]
@alexott the problem seems to be resolved for me already (using clojure 1.8, and incanter 1.9.x), sorry for disturbance. However 1.5.x incanter versions seems still having the problem with newer clojure releases. Thanks for your response!
