### ISSUE TITLE
can't install artifact bouncycastle:bctsp-jdk14:jar:138 in central

### ISSUE THREAD

**Issue by stardiviner** [incanter/incanter#388]
When I execute command:
```
clj -Sdeps '{:deps {incanter {:mvn/version "1.9.2"}}}'
```
to install Incanter.
I got error:
```
Error building classpath. Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:260)
        at clojure.tools.deps.alpha.extensions.maven$eval679$fn__681.invoke(maven.clj:93)
        at clojure.lang.MultiFn.invoke(MultiFn.java:243)
        at clojure.tools.deps.alpha$lib_paths$fn__1011.invoke(alpha.clj:190)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__7839.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__7839.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6748)
        at clojure.core$reduce.invoke(core.clj:6730)
        at clojure.tools.deps.alpha$lib_paths.invokeStatic(alpha.clj:186)
        at clojure.tools.deps.alpha$lib_paths.invoke(alpha.clj:184)
        at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:216)
        at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:197)
        at clojure.tools.deps.alpha.script.make_classpath$create_classpath.invokeStatic(make_classpath.clj:59)
        at clojure.tools.deps.alpha.script.make_classpath$create_classpath.invoke(make_classpath.clj:52)
        at clojure.tools.deps.alpha.script.make_classpath$run.invokeStatic(make_classpath.clj:70)
        at clojure.tools.deps.alpha.script.make_classpath$run.invoke(make_classpath.clj:64)
        at clojure.tools.deps.alpha.script.make_classpath$_main.invokeStatic(make_classpath.clj:103)
        at clojure.tools.deps.alpha.script.make_classpath$_main.doInvoke(make_classpath.clj:78)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.main$main_opt.invokeStatic(main.clj:317)
        at clojure.main$main_opt.invoke(main.clj:313)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
        ... 32 more
```

I tried re-execute command many times. Still this error.
But I see it exist in Maven Center: https://mvnrepository.com/artifact/org.bouncycastle/bctsp-jdk14
I also tried to install this artifact manually:
```
wget -c "http://central.maven.org/maven2/org/bouncycastle/bctsp-jdk14/1.38/bctsp-jdk14-1.38.jar"
mvn install:install-file \
    -Dfile=bctsp-jdk14-1.38.jar -DgroupId=org.bouncycastle \
    -DartifactId=bctsp-jdk14 -Dversion=1.38 -Dpackaging=jar
```
Then I execute install command again, still error. weird.

**Comment by campeterson** [comment]
@stardiviner  This is not as nice, but I've found that it works:

    clj -Sdeps '{:deps {incanter/incanter-core {:mvn/version "1.9.2"} incanter/incanter-charts {:mvn/version "1.9.2"} incanter/incanter-io {:mvn/version "1.9.2"}} }'

Haven't dug into why yet.

**Comment by campeterson** [comment]
Related to: https://github.com/incanter/incanter/issues/365

**Comment by stardiviner** [comment]
> clj -Sdeps '{:deps {incanter/incanter-core {:mvn/version "1.9.2"} incanter/incanter-charts {:mvn/version "1.9.2"} incanter/incanter-io {:mvn/version "1.9.2"}} }'

Confirmed works on this.
But other Incanter parts does not work. I tried all of them. Here is the results:

#+NAME: clj install incanter
#+begin_src shell
clj -Sdeps '{:deps {incanter {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:52:45> da8dfb3eff81c15fbd7e42304a32a1627b10f98b]:
: Error building classpath. Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
: at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)

#+NAME: clj install incanter-core
#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-core {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-13 20:33:13> fd02c1646eb5d5f0a3e6edeb6b6b973719e969c9]: clj install incanter-core
: Clojure 1.9.0
: user=> 

#+RESULTS[<2018-05-13 20:08:56> 17f8b802ff719faf6d4e1d2cfdcb8bbf92f18575]:

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-io {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:52:08> e82a451b7632ebd361f616bda098e4a0171e14e7]:
: Clojure 1.9.0
: user=> 

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-charts {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:52:19> c587a082bd991578dbd5f4bf801ec140cbaccd85]:
: Clojure 1.9.0
: user=> 

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-pdf {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:52:45> da8dfb3eff81c15fbd7e42304a32a1627b10f98b]:
: Error building classpath. Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
: at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-svg {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:53:07> 130b3b6aacaa3b2812be085891c485ae7fe723c4]:
: Clojure 1.9.0
: user=> 

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-sql {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:53:14> 238cd17f7a5e06d71ee4c75354ee1471ed25d810]:
: Clojure 1.9.0
: user=> 

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-mongodb {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:53:21> 578f1a4ab815dbd10f590fc65a70cf584f1d3611]:
: Clojure 1.9.0
: user=> 

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-excel {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:53:28> 8527847f1effd92f72206dd56607671f357264c8]:
: Clojure 1.9.0
: user=> 

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-processing {:mvn/version "1.3.0"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:53:57> 540c7650eac88c063d0d905c7fd44033b2cd94b3]:
: Clojure 1.9.0
: user=> 

#+begin_src shell
clj -Sdeps '{:deps {incanter/incanter-zoo {:mvn/version "1.9.2"}}}'
#+end_src

#+RESULTS[<2018-05-15 14:54:18> aa4d3b3559c79bc0720e40fd006d908d7fba8d48]:
: Clojure 1.9.0
: user=>

**Comment by stardiviner** [comment]
I install artifact `org.bouncycastle:bctsp-jdk14:jar:1.46` instead of `bouncycastle:bctsp-jdk14:jar:138` is fine. Don't know what's the difference between this two artifacts. Maybe incanter should use dependency `org.bouncycastle:bctsp-jdk14:jar:1.46`.

- http://search.maven.org/#artifactdetails%7Cbouncycastle%7Cbctsp-jdk14%7C138%7Cjar
- http://search.maven.org/#artifactdetails%7Corg.bouncycastle%7Cbctsp-jdk14%7C1.46%7Cjar

**Comment by stardiviner** [comment]
Seems because `bouncycastle.bctsp-jdk14` does not have "*jar*" http://search.maven.org/#search%7Cga%7C1%7Cbouncycastle

**Comment by stardiviner** [comment]
Then I locate this artifact dependency in `com.lowagie/itext`, modify it's POM file dependency from "`bouncycastle.bctsp-jdk14:138`" into "`org.bouncycastle.bctsp-jdk14:1.46`". Then it works now.

**Comment by alexott** [comment]
Should be fixed now, but I'll wait several days until next release...

**Comment by stardiviner** [comment]
I have a question, I manually modified `com.lowagie/itext` POM dependencies, will it be override by furture Incanter upgrade?

**Comment by alexott** [comment]
Your changes will stay until you won't remove the files.

But it's better not to modify POM dependency of the package, but instead use exclusions + explicit inclusions of the dependencies. 

And I really surprised by this issue - it worked for many years, and we didn't have this problem before

**Comment by middlesphere** [comment]
Unfortunately, a bug is still here:

> mike@mikebook01 ~> clojure -A:rebel -Sdeps '{:deps {incanter {:mvn/version "1.9.3"}}}'
Error building classpath. Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)
org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact bouncycastle:bctsp-jdk14:jar:138 in central (https://repo1.maven.org/maven2/)

**Comment by plexus** [comment]
It seems bouncycastle-bctsp-jdk14 used to have a version 138 on Maven Central, but it was moved to 1.38 (I guess it was a typo)

https://mvnrepository.com/artifact/bouncycastle/bctsp-jdk14/138

![2018-08-01-113635_426x104_scrot](https://user-images.githubusercontent.com/32212/43513875-2f0e7f58-957f-11e8-9608-159ea92513b7.png)

So my guess is this used to work, but now this artifact+version "disappeared".

However, com.lowagie.itext still depends on version 138, up to version 4.2.1. 

https://mvnrepository.com/artifact/com.lowagie/itext/4.2.1

After this they moved to a new group/artifact id, so the next available version is com.itextpdf.itextpdf 5.0.6.

![2018-08-01-113930_513x219_scrot](https://user-images.githubusercontent.com/32212/43514086-ae423742-957f-11e8-8a56-84ec5a786fc2.png)

This one correctly relies on bouncycastle 1.38, and later 1.46, instead 138.

So upgrading from itext 2 to itext 5 would solve the issue, but I'm guessing it'd be a good bit of work.

https://itextpdf.com/itext-5-vs-itext-2

Meanwhile incanter-pdf has added a dependency on bouncycastle 1.38, which presumably clears things up in Leiningen, but clojure CLI uses a different resolution algorithm, which seems to favor the version 138 as requested by itext.

Maybe someone should upload version 138 to Clojars so that it resolves again... I can understand it was probably a mistake to release it with that version number, but meanwhile people are relying on it, it seems a bit irresponsible from Maven Central to allow artifacts to simply disappear like that. (I do not rule out I may be missing some subtleties here, maybe get a second opinion on whether this would be a good idea.)

**Comment by didibus** [comment]
So this isn't released yet? Why are we waiting to make a new release?

**Comment by sesm** [comment]
Bumped into the same issue too.
Is there a workaround that can be applied from deps.edn directly?
I tried it like this, but it doesn't help:
```
{:deps
  {incanter {:mvn/version "1.9.3"}}
  :aliases {
    :bctsp {:override-deps {org.bouncycastle/bctsp-jdk14 {:mvn/version "1.38"}}}
  }
}
```

**Comment by onetom** [comment]
Based on how `quil` was fixed in https://github.com/quil/quil/pull/276/commits/7f0e7b955224fbb5b62890ef8d5af028e5cc3338 this fixes `incanter`:
```bash
clj -Sdeps '
{:deps {incanter                     {:mvn/version "1.9.3"}
        com.lowagie/itext            {:mvn/version "2.1.7"
                                      :exclusions  [bouncycastle/bctsp-jdk14]}
        org.bouncycastle/bctsp-jdk14 {:mvn/version "1.38"}}}' \
-e "(use '(incanter core charts)) (view (function-plot sin -4 4))"
```

Output should look like:
```
#object[org.jfree.chart.ChartFrame 0x7ce069de "org.jfree.chart.ChartFrame[frame0,0,23,500x400,layout=java.awt.BorderLayout,title=Incanter Plot,resizable,normal,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,22,500x378,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777675,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]"]
```

and a graphical window should appear with the function plot.

The trick is that the the buggy bouncy castle had simply a `bouncycastle` artifact group-id, but the fixed version has `org.bouncycastle`.

**Comment by onetom** [comment]
Ideally, you should also be able to just use the upcoming 1.9.4 version directly from git, like:
```
{:deps
 {incanter {:git/url "https://github.com/incanter/incanter.git"
            :sha     "e0a03aac237fcc60587278a36bd2e76266fc6356"}}}```
BUT, this does NOT work currently, because it needs some Clojure CLI related
config files in the repo.

**Comment by johanatan** [comment]
This is still happening in late summer 2023 (tools.deps).

**Comment by tomdl89** [comment]
For posterity, having got the same error just today, I got Incanter deps brought in successfully by adding these lines to my deps.edn:
```clojure
org.bouncycastle/bcprov-jdk15on {:mvn/version "1.70"}
net.mikera/core.matrix {:mvn/version "0.63.0"}
incanter/incanter {:mvn/version "1.9.3"
                   :exclusions [bouncycastle/bctsp-jdk14]}
```
